server {
    listen 3000;
    proxy_read_timeout 120s;
    proxy_connect_timeout 120s;
    proxy_send_timeout 120s;
    location /apps { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; }
    location /app { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; }
    location /install { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; }
    location /signin { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; }
    location /_next { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; }
    location /console { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; }
    location /chatflow { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; }
    location /workflow { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; }
    location /chat { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; }
    location /v1 { proxy_pass http://10.0.129.128; proxy_set_header Host 10.0.129.128; proxy_read_timeout 120s; }
    location /api { proxy_pass http://localhost:3001; proxy_set_header Host $host; }
    location / { proxy_pass http://localhost:3001; proxy_set_header Host $host; }
}
